"""add_managed_by_to_agents

Revision ID: 1872e2cdeb1b
Revises: c8d6cbe90fb3
Create Date: 2026-03-04 11:42:15.929213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1872e2cdeb1b'
down_revision: Union[str, Sequence[str], None] = 'c8d6cbe90fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('agents', sa.Column('managed_by', sa.String(length=20), nullable=False, server_default='vscode'))
    op.alter_column('agents', 'managed_by', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'managed_by')
    # ### end Alembic commands ###
